#!/usr/bin/env bash
#
# Build strongSwan under MinGW64 (charon-svc, swanctl, pki).
# Requires that scripts/setup-msys2.sh has run and third_party/strongswan/
# contains a strongSwan source tree (see scripts/fetch-deps.sh).
#
# Usage:  ./scripts/build-charon.sh [clean]
#
set -euo pipefail

if [[ "${MSYSTEM:-}" != "MINGW64" ]]; then
    echo "ERROR: must run in an MSYS2 MINGW64 shell." >&2
    exit 1
fi

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="$repo_root/third_party/strongswan"

if [[ ! -d "$src" ]]; then
    echo "ERROR: $src missing. Run scripts/fetch-deps.sh first." >&2
    exit 1
fi

cd "$src"

# -----------------------------------------------------------------------------
# Mount our out-of-tree kernel-wintun plugin into the strongSwan source tree.
# Idempotent: source files via copy_if_different, configure.ac/Makefile.am
# touched only when a marker is absent (greppable).
# -----------------------------------------------------------------------------
echo "==> integrate kernel-wintun plugin"

plugin_src="$repo_root/src/plugin/kernel-wintun"
plugin_dst="$src/src/libcharon/plugins/kernel_wintun"
mkdir -p "$plugin_dst"
for f in kernel_wintun_plugin.h   kernel_wintun_plugin.c  \
         kernel_wintun_ipsec.h    kernel_wintun_ipsec.c   \
         kernel_wintun_router.h   kernel_wintun_router.c  \
         kernel_wintun_capture.h  kernel_wintun_capture.c \
         kernel_wintun_session.h \
         Makefile.am; do
    cp -u "$plugin_src/$f" "$plugin_dst/$f"
done

# The router calls Wintun via wintun_loader; mount the loader and the
# upstream wintun.h header into the plugin directory so the autotools
# build can compile + include them locally.
cp -u "$repo_root/src/wintun/wintun_loader.h"      "$plugin_dst/"
cp -u "$repo_root/src/wintun/wintun_loader.c"      "$plugin_dst/"
cp -u "$repo_root/third_party/wintun/include/wintun.h" "$plugin_dst/"

# Same for the WinDivert loader + header (M7 step 2).
cp -u "$repo_root/src/windivert/windivert_loader.h"        "$plugin_dst/"
cp -u "$repo_root/src/windivert/windivert_loader.c"        "$plugin_dst/"
cp -u "$repo_root/third_party/windivert/include/windivert.h" "$plugin_dst/"

# Patch configure.ac (5 sites, all guarded by a grep marker)
ca="configure.ac"
patched=0

if ! grep -q "kernel-wintun" "$ca"; then
    echo "    patching $ca"
    # 1) ARG_ENABL_SET — insert directly after kernel-wfp
    sed -i '/^ARG_ENABL_SET(\[kernel-wfp\]/a\
ARG_ENABL_SET([kernel-wintun],  [enable Wintun-based userspace IPsec backend (out-of-tree).])' "$ca"

    # 2) Auto-enable libipsec when kernel-wintun is on (mirrors kernel-libipsec)
    sed -i '/^if test x\$kernel_libipsec = xtrue; then$/,/^fi$/{
        /^fi$/a\
\
if test x$kernel_wintun = xtrue; then\
\tlibipsec=true;\
fi
    }' "$ca"

    # 3) ADD_PLUGIN — alongside kernel-iph
    sed -i '/^ADD_PLUGIN(\[kernel-iph\]/a\
ADD_PLUGIN([kernel-wintun],        [c charon])' "$ca"

    # 4) AM_CONDITIONAL — alongside USE_KERNEL_IPH
    sed -i '/^AM_CONDITIONAL(USE_KERNEL_IPH/a\
AM_CONDITIONAL(USE_KERNEL_WINTUN, test x$kernel_wintun = xtrue)' "$ca"

    # 5) AC_CONFIG_FILES — append the Makefile entry
    sed -i '/src\/libcharon\/plugins\/kernel_iph\/Makefile/a\
\tsrc/libcharon/plugins/kernel_wintun/Makefile' "$ca"

    patched=1
fi

# Apply *.patch files from patches/ (idempotent via patch --dry-run --reverse)
for p in "$repo_root"/patches/*.patch; do
    [[ -f "$p" ]] || continue
    name="$(basename "$p")"
    if patch -p1 --dry-run --reverse --silent < "$p" >/dev/null 2>&1; then
        echo "    $name already applied"
    elif patch -p1 --dry-run --silent < "$p" >/dev/null 2>&1; then
        echo "    apply $name"
        patch -p1 --silent < "$p"
        patched=1
    else
        echo "ERROR: $name does not apply (neither forward nor reverse)" >&2
        exit 1
    fi
done

# Patch libcharon/Makefile.am — insert the USE_KERNEL_WINTUN block
lcma="src/libcharon/Makefile.am"
if ! grep -q "USE_KERNEL_WINTUN" "$lcma"; then
    echo "    patching $lcma"
    # insert right after the USE_KERNEL_IPH block
    sed -i '/^if USE_KERNEL_IPH$/,/^endif$/{
        /^endif$/a\
\
if USE_KERNEL_WINTUN\
  SUBDIRS += plugins/kernel_wintun\
if MONOLITHIC\
  libcharon_la_LIBADD += plugins/kernel_wintun/libstrongswan-kernel-wintun.la\
endif\
endif
    }' "$lcma"
    patched=1
fi

# GitHub source trees lack ./configure — autoreconf creates it. Also re-run
# whenever we just patched the autotools inputs.
if [[ ! -x configure ]] || [[ "${1:-}" == "clean" ]] || [[ $patched -eq 1 ]]; then
    echo "==> autoreconf"
    autoreconf -i

    # plugin_constructors.c is regenerated by make ONLY when the generator
    # .py is newer than the .c — NOT when c_plugins / s_plugins (configure
    # variables) change. Forcing the .c gone makes make rebuild it.
    rm -f src/libcharon/plugin_constructors.c \
          src/libstrongswan/plugin_constructors.c
fi

if [[ "${1:-}" == "clean" ]]; then
    echo "==> distclean"
    make distclean 2>/dev/null || true
fi

# Configure flags follow the official strongSwan-on-Windows recipe:
# - monolithic + static: every plugin is statically linked into libcharon
# - socket-win: Windows-specific UDP socket layer
# - kernel-iph + kernel-wfp: existing Windows backends (we keep them around;
#   kernel-wintun displaces kernel-wfp at runtime via plugin config)
# - openssl as crypto backend
# - kernel-wintun: our own plugin, mounted above
echo "==> configure"
CFLAGS="-g -O2 -Wall -Wno-pointer-sign -Wno-format-security -Wno-format -mno-ms-bitfields" \
./configure \
    --prefix="$repo_root/build/charon-install" \
    --disable-defaults \
    --enable-monolithic \
    --enable-static \
    --enable-svc \
    --enable-ikev2 --enable-ikev1 \
    --enable-nonce --enable-pem --enable-pkcs1 \
    --enable-x509 --enable-pubkey \
    --enable-openssl \
    --enable-socket-win \
    --enable-kernel-wfp --enable-kernel-iph \
    --enable-kernel-wintun \
    --enable-eap-identity --enable-eap-mschapv2 \
    --enable-md4 \
    --enable-swanctl \
    --enable-vici \
    --with-swanctldir=swanctl \
    --with-strongswan-conf=strongswan.conf

echo "==> make"
make -j"$(nproc)"

echo "==> make install"
make install

# Copy DLLs from lib/bin/ next to the binaries (autotools default is
# Linux-centric and places them where the Windows loader cannot find them).
prefix="$repo_root/build/charon-install"
echo "==> consolidate DLLs into bin/ and sbin/"
cp -u "$prefix/lib/bin/"*.dll "$prefix/bin/" 2>/dev/null || true
cp -u "$prefix/lib/bin/"*.dll "$prefix/sbin/" 2>/dev/null || true

# Deploy transitive MinGW runtime DLLs alongside the exes
echo "==> deploy MinGW runtime DLLs"
bash "$repo_root/scripts/deploy-mingw-deps.sh" "$prefix/bin/charon-svc.exe" /mingw64/bin
bash "$repo_root/scripts/deploy-mingw-deps.sh" "$prefix/sbin/swanctl.exe"   /mingw64/bin

# wintun.dll must sit next to charon-svc.exe — kernel-wintun's wintun_load()
# uses LOAD_LIBRARY_SEARCH_APPLICATION_DIR for safety.
wintun_dll="$repo_root/third_party/wintun/bin/amd64/wintun.dll"
if [[ -f "$wintun_dll" ]]; then
    echo "==> deploy wintun.dll"
    cp -u "$wintun_dll" "$prefix/bin/wintun.dll"
fi

# WinDivert.dll auto-installs WinDivert64.sys on the first WinDivertOpen()
# call; both files must sit next to the .exe that loads the DLL. We deploy
# them to bin/ alongside charon-svc.exe.
windivert_dll="$repo_root/third_party/windivert/x64/WinDivert.dll"
windivert_sys="$repo_root/third_party/windivert/x64/WinDivert64.sys"
if [[ -f "$windivert_dll" && -f "$windivert_sys" ]]; then
    echo "==> deploy WinDivert.dll + WinDivert64.sys"
    cp -u "$windivert_dll" "$prefix/bin/WinDivert.dll"
    cp -u "$windivert_sys" "$prefix/bin/WinDivert64.sys"
fi

# Roll out default config templates into etc/ if they don't exist yet.
# User-edited files are never overwritten.
echo "==> install default config templates to etc/"
mkdir -p "$prefix/etc/strongswan.d/charon" "$prefix/etc/swanctl"
[[ -f "$prefix/etc/strongswan.conf" ]] || \
    cp "$prefix/share/strongswan/templates/config/strongswan.conf" "$prefix/etc/"
for f in "$prefix/share/strongswan/templates/config/strongswan.d/"*.conf; do
    name="$(basename "$f")"
    [[ -f "$prefix/etc/strongswan.d/$name" ]] || cp "$f" "$prefix/etc/strongswan.d/"
done
for f in "$prefix/share/strongswan/templates/config/plugins/"*.conf; do
    name="$(basename "$f")"
    [[ -f "$prefix/etc/strongswan.d/charon/$name" ]] || \
        cp "$f" "$prefix/etc/strongswan.d/charon/"
done

echo
echo "DONE.  charon-svc:  $prefix/bin/charon-svc.exe"
echo "       swanctl:    $prefix/sbin/swanctl.exe"
echo "       config:     $prefix/etc/strongswan.conf"
echo
echo "Run with: STRONGSWAN_CONF=$prefix/etc/strongswan.conf $prefix/bin/charon-svc.exe"
