# dhc-vpn -- Windows installer (M9a, internal-tester grade)
#
# What this does:
#   1. Copy program files to %ProgramFiles%\dhc-vpn\
#   2. Lay out %ProgramData%\dhc-vpn\swanctl\ with default subdirs
#      (x509, x509ca, private, conf.d, secrets.d) + a starter swanctl.conf
#      that includes conf.d/*.conf
#   3. Register charon-svc as a Windows Service (manual start, LocalSystem)
#   4. Open UDP/500 + UDP/4500 in the firewall (inbound)
#   5. Drop a Start-Menu shortcut for the GUI
#
# What this does NOT do:
#   - Install Wintun / WinDivert drivers. Both are user-space-loaded on
#     first use by the daemon (admin context = LocalSystem, which is fine).
#   - Sign anything. Use signtool separately if needed.
#   - Auto-start the service. Tester decides when to enable it.
#
# Run as Administrator.  Layout of the source tree this expects to be
# called from:
#
#   <pkg-root>\
#     bin\         charon-svc.exe + DLLs + wintun.dll + WinDivert*
#     sbin\        swanctl.exe + DLLs
#     etc\         strongswan.conf + strongswan.d/...
#     gui\         dhc-vpn.exe + Qt6 DLLs + plugins\...
#     scripts\     install.ps1, uninstall.ps1
#
# Usage:
#   PS> .\install.ps1
#   PS> .\install.ps1 -InstallDir 'D:\dhc-vpn'
#   PS> .\install.ps1 -DataDir    'D:\ProgramData\dhc-vpn'

[CmdletBinding()]
param(
    [string]$InstallDir = (Join-Path $env:ProgramFiles 'dhc-vpn'),
    [string]$DataDir    = (Join-Path $env:ProgramData  'dhc-vpn'),
    [string]$ServiceName = 'charon-svc',
    [switch]$NoFirewall,
    [switch]$NoStartMenu
)

$ErrorActionPreference = 'Stop'

# ---- prerequisites -----------------------------------------------------

function Assert-Admin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($id)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'install.ps1 must be run as Administrator.'
    }
}

Assert-Admin

# Source root = parent of the directory holding this script.
$here = Split-Path -Parent $PSCommandPath
$src  = Split-Path -Parent $here

foreach ($sub in 'bin','sbin','etc','gui') {
    $p = Join-Path $src $sub
    if (-not (Test-Path $p)) {
        throw "Source directory not found: $p (running install.ps1 from the wrong place?)"
    }
}

Write-Host "Installing dhc-vpn"
Write-Host "  source : $src"
Write-Host "  install: $InstallDir"
Write-Host "  data   : $DataDir"
Write-Host ''

# ---- stop the service if it already exists -----------------------------

$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    if ($existing.Status -ne 'Stopped') {
        Write-Host "Stopping existing $ServiceName service..."
        Stop-Service -Name $ServiceName -Force
        Start-Sleep -Seconds 1
    }
}

# ---- copy program files ------------------------------------------------

Write-Host "Copying program files..."
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
foreach ($sub in 'bin','sbin','etc','gui') {
    $dst = Join-Path $InstallDir $sub
    if (Test-Path $dst) { Remove-Item -Recurse -Force $dst }
    Copy-Item -Recurse -Force (Join-Path $src $sub) $dst
}

# ---- lay out ProgramData (idempotent: never clobber user data) ---------

Write-Host "Preparing data directory..."
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
$swanctlDir = Join-Path $DataDir 'swanctl'
foreach ($sub in 'x509','x509ca','private','conf.d','secrets.d') {
    New-Item -ItemType Directory -Force -Path (Join-Path $swanctlDir $sub) | Out-Null
}
New-Item -ItemType Directory -Force -Path (Join-Path $DataDir 'logs') | Out-Null

# Default swanctl.conf (only created if missing -- never overwritten).
$swanctlConf = Join-Path $swanctlDir 'swanctl.conf'
if (-not (Test-Path $swanctlConf)) {
    @'
# dhc-vpn -- swanctl configuration
#
# GUI-managed profiles live in conf.d/<name>.conf and are picked up via
# the include below. EAP password blobs (DPAPI-encrypted) sit in
# secrets.d/<name>.dat and are materialized into transient
# _eap-<name>.secret.conf files only at connect time.
include conf.d/*.conf
'@ | Set-Content -Path $swanctlConf -Encoding ASCII
}

# Override etc/strongswan.conf paths so charon-svc reads from $DataDir.
# We do this by writing a one-line wrapper in the install dir's etc/
# that includes the upstream file, then point STRONGSWAN_CONF at it
# via a service-level env var.
$etcWrapper = Join-Path $InstallDir 'etc\strongswan.conf'
$dataLogPath = (Join-Path $DataDir 'logs\charon.log').Replace('\','/')
@"
# generated by install.ps1 -- charon-svc reads this at startup.
charon {
    load_modular = yes
    user = ''
    plugins {
        include strongswan.d/charon/*.conf
    }
    filelog {
        charon-log {
            path = $dataLogPath
            time_format = %b %e %T
            ike_name = yes
            append = yes
            default = 1
            flush_line = yes
        }
    }
}
include strongswan.d/*.conf
"@ | Set-Content -Path $etcWrapper -Encoding ASCII

# ---- service registration ----------------------------------------------

$exePath = Join-Path $InstallDir 'bin\charon-svc.exe'
if (-not (Test-Path $exePath)) {
    throw "charon-svc.exe missing at $exePath"
}

if ($existing) {
    Write-Host "Updating existing $ServiceName service..."
    & sc.exe config $ServiceName binPath= "`"$exePath`"" start= demand obj= LocalSystem | Out-Null
} else {
    Write-Host "Registering $ServiceName service..."
    & sc.exe create $ServiceName binPath= "`"$exePath`"" start= demand obj= LocalSystem DisplayName= 'dhc-vpn (charon)' | Out-Null
}
& sc.exe description $ServiceName 'strongSwan IKEv2 daemon for dhc-vpn (Wintun + WinDivert backend).' | Out-Null

# Loosen the service ACL so any logged-in user can start/stop charon-svc.
# Default Windows ACL only grants START/STOP to admins, but the GUI runs
# unelevated and needs to spin the daemon up on Connect. Grants AU
# (Authenticated Users) SERVICE_START + SERVICE_STOP + read perms; SY/BA
# entries stay untouched. Trade-off: any local user can stop the VPN.
$existingSd = (& sc.exe sdshow $ServiceName | Out-String).Trim()
if ($existingSd -notmatch '\(A;[^)]*;AU\)') {
    Write-Host "Granting service start/stop to Authenticated Users..."
    # Insert the AU ACE before the SACL section if present, else append.
    # Plain string-split: a regex on [^S]* is fooled by the literal 'S' in
    # service access flags like CCLCSW / SD / etc.
    $sIdx = $existingSd.IndexOf('S:')
    if ($sIdx -gt 0) {
        $dPart = $existingSd.Substring(0, $sIdx)
        $sPart = $existingSd.Substring($sIdx)
    } else {
        $dPart = $existingSd
        $sPart = ''
    }
    $newSd = $dPart + '(A;;CCLCSWLOCRRPWP;;;AU)' + $sPart
    & sc.exe sdset $ServiceName $newSd | Out-Null
}

# Service-scoped environment so charon-svc finds the per-machine config.
# HKLM\SYSTEM\CurrentControlSet\Services\<name>\Environment is the
# documented place; the service manager exports these to the child.
$svcKey = "HKLM:\SYSTEM\CurrentControlSet\Services\$ServiceName"
if (-not (Test-Path $svcKey)) {
    throw "service registry key missing right after sc create -- this should not happen"
}
$envValue = @(
    "STRONGSWAN_CONF=$etcWrapper",
    "SWANCTL_DIR=$swanctlDir"
)
New-ItemProperty -Path $svcKey -Name Environment -PropertyType MultiString -Value $envValue -Force | Out-Null

# ---- firewall ----------------------------------------------------------

if (-not $NoFirewall) {
    Write-Host "Configuring firewall (UDP/500 + UDP/4500 inbound)..."
    foreach ($port in 500, 4500) {
        $name = "dhc-vpn IKE UDP/$port"
        if (-not (Get-NetFirewallRule -DisplayName $name -ErrorAction SilentlyContinue)) {
            New-NetFirewallRule -DisplayName $name `
                -Direction Inbound -Action Allow `
                -Protocol UDP -LocalPort $port `
                -Profile Any -Program $exePath | Out-Null
        }
    }

    # Allow ALL inbound on the wintun adapter regardless of network profile.
    # Without this, Windows treats a fresh wintun adapter as "Public" and
    # silently blocks ICMP/inbound replies from the VPN -- ping/curl through
    # the tunnel just times out. Rule is interface-bound so it only loosens
    # firewall on traffic that already came out of an authenticated ESP SA.
    #
    # CAVEAT: New-NetFirewallRule -InterfaceAlias requires the adapter to
    # EXIST at rule-creation time, but the wintun adapter only comes up
    # when the daemon is started for the first time. On a fresh install
    # this throws. We swallow the error and warn -- the GUI will retry
    # rule creation after the first successful connect.
    $tunRule = 'dhc-vpn allow inbound on wintun'
    if (-not (Get-NetFirewallRule -DisplayName $tunRule -ErrorAction SilentlyContinue)) {
        try {
            New-NetFirewallRule -DisplayName $tunRule `
                -Direction Inbound -Action Allow `
                -InterfaceAlias 'dhc-vpn' `
                -Profile Any -EA Stop | Out-Null
        } catch {
            Write-Host "  (note: dhc-vpn adapter not up at install time, so the"
            Write-Host "         wintun-inbound firewall rule could not be created."
            Write-Host "         After first successful connect, run from admin PS:"
            Write-Host "           Set-NetConnectionProfile -InterfaceAlias dhc-vpn ``"
            Write-Host "             -NetworkCategory Private"
            Write-Host "         OR add the rule explicitly:"
            Write-Host "           New-NetFirewallRule -DisplayName '$tunRule' ``"
            Write-Host "             -Direction Inbound -Action Allow ``"
            Write-Host "             -InterfaceAlias dhc-vpn -Profile Any)"
        }
    }
}

# ---- Start Menu shortcut ----------------------------------------------

if (-not $NoStartMenu) {
    $guiExe = Join-Path $InstallDir 'gui\dhc-vpn.exe'
    if (Test-Path $guiExe) {
        Write-Host "Creating Start Menu shortcut..."
        $startMenu = Join-Path $env:ProgramData 'Microsoft\Windows\Start Menu\Programs'
        $lnk = Join-Path $startMenu 'dhc-vpn.lnk'
        $shell = New-Object -ComObject WScript.Shell
        $shortcut = $shell.CreateShortcut($lnk)
        $shortcut.TargetPath = $guiExe
        $shortcut.WorkingDirectory = (Split-Path -Parent $guiExe)
        $shortcut.IconLocation = "$guiExe,0"
        $shortcut.Description = 'dhc-vpn (IKEv2 client)'
        $shortcut.Save()
    }
}

Write-Host ''
Write-Host 'Install complete.'
Write-Host ''
Write-Host "  Start service:   sc.exe start $ServiceName"
Write-Host "  Stop service:    sc.exe stop  $ServiceName"
Write-Host "  Logs:            $($DataDir)\logs\charon.log"
Write-Host "  GUI:             $InstallDir\gui\dhc-vpn.exe"
Write-Host ''
Write-Host 'The GUI does not start charon-svc itself -- start the service'
Write-Host 'first (or set start= auto via sc.exe).'
